force-app/main/default/objects/Highlight_Badge_Action__c/Highlight_Badge_Action__c.object-meta.xml
<CustomObject>
    <description>A customizable action associated with a Highlight Badge that allows for user interaction and automated tasks</description>
    <label>Highlight Badge Action</label>
    <nameField>
        <label>Highlight Badge Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Highlight_Badge_Definition__c.field-meta.xml
<CustomField>
    <fullName>Highlight_Badge_Definition__c</fullName>
    <label>Highlight Badge Definition</label>
    <referenceTo>Highlight_Badge_Definition__c</referenceTo>
    <relationshipLabel>Highlight Badge Actions</relationshipLabel>
    <relationshipName>Highlight_Badge_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>Use icon names from the SLDS library (e.g. standard:actions_and_buttons)</description>
    <inlineHelpText>Use icon names from the SLDS library (e.g. standard:actions_and_buttons)</inlineHelpText>
    <label>Icon Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>base</fullName>
            </value>
            <value>
                <fullName>neutral</fullName>
            </value>
            <value>
                <fullName>brand</fullName>
            </value>
            <value>
                <fullName>brand-outline</fullName>
            </value>
            <value>
                <fullName>destructive</fullName>
            </value>
            <value>
                <fullName>destructive-text</fullName>
            </value>
            <value>
                <fullName>inverse</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/Highlight_Badge_Definition__c.object-meta.xml
<CustomObject>
    <description>Configuration for an individual highlight badge</description>
    <label>Highlight Badge Definition</label>
    <nameField>
        <label>Highlight Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, an alert will display to the user when the page loads</description>
    <inlineHelpText>If checked, an alert will display to the user when the page loads</inlineHelpText>
    <label>Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Alert_Frequency__c</fullName>
    <description>Determines how often an alert will be shown to a particular user</description>
    <inlineHelpText>Determines how often an alert will be shown to a particular user</inlineHelpText>
    <label>Alert Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always</fullName>
            </value>
            <value>
                <fullName>Once Per Session</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert_Message__c.field-meta.xml
<CustomField>
    <fullName>Alert_Message__c</fullName>
    <description>When Alert is checked, this message displays in the pop-up window a page loads. Use {!My_Custom_Field__c} syntax to display merged values from the child object</description>
    <inlineHelpText>When Alert is checked, this message displays in the pop-up window a page loads. Use {!My_Custom_Field__c} syntax to display merged values from the child object</inlineHelpText>
    <label>Alert Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert_Type__c.field-meta.xml
<CustomField>
    <fullName>Alert_Type__c</fullName>
    <label>Alert Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Modal</fullName>
            </value>
            <value>
                <fullName>Toast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <description>The background color of the displayed badge</description>
    <inlineHelpText>The background color of the displayed badge</inlineHelpText>
    <label>Background Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Common_Ancestor_Object__c.field-meta.xml
<CustomField>
    <fullName>Common_Ancestor_Object__c</fullName>
    <description>The API Name of the Salesforce object that serves as a shared ancestor or linking object between the Display Object and the Source Object</description>
    <inlineHelpText>The API Name of the Salesforce object that serves as a shared ancestor or linking object between the Display Object and the Source Object</inlineHelpText>
    <label>Common Ancestor Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Confetti__c.field-meta.xml
<CustomField>
    <fullName>Confetti__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, confetti will rain when the page loads</description>
    <inlineHelpText>If checked, confetti will rain when the page loads</inlineHelpText>
    <label>Confetti</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Confetti_Volume__c.field-meta.xml
<CustomField>
    <fullName>Confetti_Volume__c</fullName>
    <description>The quantity of confetti</description>
    <inlineHelpText>The quantity of confetti</inlineHelpText>
    <label>Confetti Volume</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>few</fullName>
            </value>
            <value>
                <fullName>normal</fullName>
            </value>
            <value>
                <fullName>plenty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Display_Object__c.field-meta.xml
<CustomField>
    <fullName>Display_Object__c</fullName>
    <description>The API Name of the Salesforce object where the Highlight Badge will appear</description>
    <inlineHelpText>The API Name of the Salesforce object where the Highlight Badge will appear</inlineHelpText>
    <label>Display Object</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Display_to_Ancestor_Path__c.field-meta.xml
<CustomField>
    <fullName>Display_to_Ancestor_Path__c</fullName>
    <description>The API path from the Display Object to the Common Ancestor Object</description>
    <inlineHelpText>The API path from the Display Object to the Common Ancestor Object</inlineHelpText>
    <label>Display to Ancestor Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <description>Additional criteria to include in the WHERE clause of the SOQL query</description>
    <inlineHelpText>Additional criteria to include in the WHERE clause of the SOQL query</inlineHelpText>
    <label>Filter Criteria</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>Use icon names from the SLDS library (e.g. utility:alert)</description>
    <inlineHelpText>Use icon names from the SLDS library (e.g. utility:alert)</inlineHelpText>
    <label>Icon Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Include_Label_in_Toast__c.field-meta.xml
<CustomField>
    <fullName>Include_Label_in_Toast__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the Label will be displayed as the toast&apos;s title.</description>
    <inlineHelpText>If checked, the Label will be displayed as the toast&apos;s title.</inlineHelpText>
    <label>Include Label in Toast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The label of the displayed badge</description>
    <inlineHelpText>The label of the displayed badge</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Label_Color__c.field-meta.xml
<CustomField>
    <fullName>Label_Color__c</fullName>
    <description>The label text color of the displayed badge</description>
    <inlineHelpText>The label text color of the displayed badge</inlineHelpText>
    <label>Label Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <description>The maximum number of badges to show for this badge definition</description>
    <inlineHelpText>The maximum number of badges to show for this badge definition</inlineHelpText>
    <label>Limit</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <description>Optionally, define the order in which badges are displayed (e.g. LastModifiedDate DESC)</description>
    <inlineHelpText>Optionally, define the order in which badges are displayed (e.g. LastModifiedDate DESC)</inlineHelpText>
    <label>Order By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_Detail_Fields__c.field-meta.xml
<CustomField>
    <fullName>Source_Detail_Fields__c</fullName>
    <description>Enter API field names, separated by commas, for any fields from the Source Object that should be displayed when a user selects a badge</description>
    <inlineHelpText>Enter API field names, separated by commas, for any fields from the Source Object that should be displayed when a user selects a badge</inlineHelpText>
    <label>Source Detail Fields</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>The API Name of the Salesforce object that is the source of the badge information. For example, a badge on a contact record displaying open cases would have a Source Object of &apos;Case&apos;.</description>
    <inlineHelpText>The API Name of the Salesforce object that is the source of the badge information. For example, a badge on a contact record displaying open cases would have a Source Object of &apos;Case&apos;.</inlineHelpText>
    <label>Source Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_to_Ancestor_Path__c.field-meta.xml
<CustomField>
    <fullName>Source_to_Ancestor_Path__c</fullName>
    <description>The API path from the Source Object to the Ancestor Object</description>
    <inlineHelpText>The API path from the Source Object to the Ancestor Object</inlineHelpText>
    <label>Source to Ancestor Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Toast_Mode__c.field-meta.xml
<CustomField>
    <fullName>Toast_Mode__c</fullName>
    <description>Determines how persistent the toast is. Valid values are: dismissible (default), remains visible until you click the close button or 3 seconds has elapsed, whichever comes first; pester, remains visible for 3 seconds and disappears automatically. No close button is provided; sticky, remains visible until you click the close button.</description>
    <inlineHelpText>Determines how persistent the toast is. Valid values are: dismissible (default), remains visible until you click the close button or 3 seconds has elapsed, whichever comes first; pester, remains visible for 3 seconds and disappears automatically. No close button is provided; sticky, remains visible until you click the close button.</inlineHelpText>
    <label>Toast Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>dismissible</fullName>
            </value>
            <value>
                <fullName>pester</fullName>
            </value>
            <value>
                <fullName>sticky</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Toast_Variant__c.field-meta.xml
<CustomField>
    <fullName>Toast_Variant__c</fullName>
    <description>Changes the appearance of the notice. Toasts inherit styling from toasts in the Lightning Design System. Valid values are: info (default), success, warning, and error.</description>
    <inlineHelpText>Changes the appearance of the notice. Toasts inherit styling from toasts in the Lightning Design System. Valid values are: info (default), success, warning, and error.</inlineHelpText>
    <label>Toast Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
            <value>
                <fullName>warning</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HighlightBadgeDefinitionSelector.cls
public with sharing class HighlightBadgeDefinitionSelector {

    private String displayObject;
    private Set<Id> additionalDefinitionIds;

    public HighlightBadgeDefinitionSelector(String displayObjectApiName) {
        this.displayObject = displayObjectApiName;
        this.additionalDefinitionIds = new Set<Id>();
    }

    public void setAdditionalDefinitions(Set<Id> definitionIds) {
        this.additionalDefinitionIds = definitionIds;
    }

    public List<Highlight_Badge_Definition__c> execute() {
        return queryForBadgeDefinitions();
    }
    
    /****************************************************
     * Query for active badge definition records
     ****************************************************/
    private List<Highlight_Badge_Definition__c> queryForBadgeDefinitions() {
        return [
            SELECT Id,
                   Name,
                   Display_Object__c,
                   Common_Ancestor_Object__c,
                   Source_Object__c,
                   Source_to_Ancestor_Path__c,
                   Display_to_Ancestor_Path__c,
                   Filter_Criteria__c,
                   Order_By__c,
                   Limit__c,
                   Source_Detail_Fields__c,
                   Label__c,
                   Icon_Name__c,
                   Background_Color__c,
                   Label_Color__c,
                   Alert__c,
                   Alert_Message__c,
                   Alert_Type__c,
                   Toast_Variant__c,
                   Toast_Mode__c,
                   Alert_Frequency__c,
                   Include_Label_in_Toast__c,
                   Confetti__c,
                   Confetti_Volume__c,
                   Confetti_Size__c,
                   (SELECT Id,
                           Sort_Order__c,
                           RecordType.Name,
                           Navigation_Type__c,
                           URL__c,
                           Open_in_New_Tab__c,
                           Flow_Type__c,
                           Flow_API_Name__c,
                           Include_Source_Record_ID__c,
                           Include_Display_Record_ID__c,
                           Label__c,
                           Variant__c,
                           Icon_Name__c,
                           Icon_Position__c
                      FROM Highlight_Badge_Actions__r
                     WHERE Active__c = true
                     ORDER BY Sort_Order__c ASC NULLS LAST)
              FROM Highlight_Badge_Definition__c
             WHERE Display_Object__c = :displayObject
               AND (Active__c = true OR Id IN :additionalDefinitionIds)
              WITH USER_MODE
             ORDER BY Sort_Order__c ASC NULLS LAST
             LIMIT 100
        ];
    }

}