force-app/main/default/objects/Highlight_Badge_Action__c/Highlight_Badge_Action__c.object-meta.xml
<CustomObject>
    <description>A customizable action associated with a Highlight Badge that allows for user interaction and automated tasks</description>
    <label>Highlight Badge Action</label>
    <nameField>
        <label>Highlight Badge Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_API_Name__c</fullName>
    <label>Flow API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Flow_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Type__c</fullName>
    <label>Flow Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autolaunched Flow</fullName>
            </value>
            <value>
                <fullName>Screen Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Highlight_Badge_Definition__c.field-meta.xml
<CustomField>
    <fullName>Highlight_Badge_Definition__c</fullName>
    <label>Highlight Badge Definition</label>
    <referenceTo>Highlight_Badge_Definition__c</referenceTo>
    <relationshipLabel>Highlight Badge Actions</relationshipLabel>
    <relationshipName>Highlight_Badge_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Include_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Include_Record_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the Record ID of the current Display Object record the user is viewing will be provided to the recordId input variable.</description>
    <inlineHelpText>If checked, the Record ID of the current Display Object record the user is viewing will be provided to the recordId input variable.</inlineHelpText>
    <label>Include Record ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Navigation_Type__c.field-meta.xml
<CustomField>
    <fullName>Navigation_Type__c</fullName>
    <label>Navigation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Knowledge Article</fullName>
            </value>
            <value>
                <fullName>Source Record</fullName>
            </value>
            <value>
                <fullName>Web Page</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Determines the order in which the action appears for its highlight badge. Lowest numbers appear first; null values appear last.</description>
    <inlineHelpText>Determines the order in which the action appears for its highlight badge. Lowest numbers appear first; null values appear last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>base</fullName>
            </value>
            <value>
                <fullName>neutral</fullName>
            </value>
            <value>
                <fullName>brand</fullName>
            </value>
            <value>
                <fullName>brand-outline</fullName>
            </value>
            <value>
                <fullName>destructive</fullName>
            </value>
            <value>
                <fullName>destructive-text</fullName>
            </value>
            <value>
                <fullName>inverse</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/Highlight_Badge_Definition__c.object-meta.xml
<CustomObject>
    <description>Configuration for an individual highlight badge</description>
    <label>Highlight Badge Definition</label>
    <nameField>
        <label>Highlight Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, an alert will display to the user when the page loads</description>
    <inlineHelpText>If checked, an alert will display to the user when the page loads</inlineHelpText>
    <label>Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Alert_Frequency__c</fullName>
    <description>Determines how often an alert will be shown to a particular user</description>
    <inlineHelpText>Determines how often an alert will be shown to a particular user</inlineHelpText>
    <label>Alert Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always</fullName>
            </value>
            <value>
                <fullName>Once Per Session</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert_Type__c.field-meta.xml
<CustomField>
    <fullName>Alert_Type__c</fullName>
    <label>Alert Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Modal</fullName>
            </value>
            <value>
                <fullName>Toast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <description>The background color of the displayed badge</description>
    <inlineHelpText>The background color of the displayed badge</inlineHelpText>
    <label>Background Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Common_Ancestor_Object__c.field-meta.xml
<CustomField>
    <fullName>Common_Ancestor_Object__c</fullName>
    <description>The API Name of the Salesforce object that serves as a shared ancestor or linking object between the Display Object and the Source Object</description>
    <inlineHelpText>The API Name of the Salesforce object that serves as a shared ancestor or linking object between the Display Object and the Source Object</inlineHelpText>
    <label>Common Ancestor Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Confetti__c.field-meta.xml
<CustomField>
    <fullName>Confetti__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, confetti will rain when the page loads</description>
    <inlineHelpText>If checked, confetti will rain when the page loads</inlineHelpText>
    <label>Confetti</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Confetti_Size__c.field-meta.xml
<CustomField>
    <fullName>Confetti_Size__c</fullName>
    <description>The size of the confetti items</description>
    <inlineHelpText>The size of the confetti items</inlineHelpText>
    <label>Confetti Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Confetti_Volume__c.field-meta.xml
<CustomField>
    <fullName>Confetti_Volume__c</fullName>
    <description>The quantity of confetti</description>
    <inlineHelpText>The quantity of confetti</inlineHelpText>
    <label>Confetti Volume</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>few</fullName>
            </value>
            <value>
                <fullName>normal</fullName>
            </value>
            <value>
                <fullName>plenty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Display_Object__c.field-meta.xml
<CustomField>
    <fullName>Display_Object__c</fullName>
    <description>The API Name of the Salesforce object where the Highlight Badge will appear</description>
    <inlineHelpText>The API Name of the Salesforce object where the Highlight Badge will appear</inlineHelpText>
    <label>Display Object</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Display_to_Ancestor_Path__c.field-meta.xml
<CustomField>
    <fullName>Display_to_Ancestor_Path__c</fullName>
    <description>The API path from the Display Object to the Common Ancestor Object</description>
    <inlineHelpText>The API path from the Display Object to the Common Ancestor Object</inlineHelpText>
    <label>Display to Ancestor Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Include_Label_in_Toast__c.field-meta.xml
<CustomField>
    <fullName>Include_Label_in_Toast__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the Label will be displayed as the toast&apos;s title.</description>
    <inlineHelpText>If checked, the Label will be displayed as the toast&apos;s title.</inlineHelpText>
    <label>Include Label in Toast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Label_Color__c.field-meta.xml
<CustomField>
    <fullName>Label_Color__c</fullName>
    <description>The label text color of the displayed badge</description>
    <inlineHelpText>The label text color of the displayed badge</inlineHelpText>
    <label>Label Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Determines the order in which badges of this type will appear. Lowest numbers appear first; null values appear last.</description>
    <inlineHelpText>Determines the order in which badges of this type will appear. Lowest numbers appear first; null values appear last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_Detail_Fields__c.field-meta.xml
<CustomField>
    <fullName>Source_Detail_Fields__c</fullName>
    <description>Enter API field names, separated by commas, for any fields from the Source Object that should be displayed when a user selects a badge</description>
    <inlineHelpText>Enter API field names, separated by commas, for any fields from the Source Object that should be displayed when a user selects a badge</inlineHelpText>
    <label>Source Detail Fields</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>The API Name of the Salesforce object that is the source of the badge information. For example, a badge on a contact record displaying open cases would have a Source Object of &apos;Case&apos;.</description>
    <inlineHelpText>The API Name of the Salesforce object that is the source of the badge information. For example, a badge on a contact record displaying open cases would have a Source Object of &apos;Case&apos;.</inlineHelpText>
    <label>Source Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Toast_Mode__c.field-meta.xml
<CustomField>
    <fullName>Toast_Mode__c</fullName>
    <description>Determines how persistent the toast is. Valid values are: dismissible (default), remains visible until you click the close button or 3 seconds has elapsed, whichever comes first; pester, remains visible for 3 seconds and disappears automatically. No close button is provided; sticky, remains visible until you click the close button.</description>
    <inlineHelpText>Determines how persistent the toast is. Valid values are: dismissible (default), remains visible until you click the close button or 3 seconds has elapsed, whichever comes first; pester, remains visible for 3 seconds and disappears automatically. No close button is provided; sticky, remains visible until you click the close button.</inlineHelpText>
    <label>Toast Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>dismissible</fullName>
            </value>
            <value>
                <fullName>pester</fullName>
            </value>
            <value>
                <fullName>sticky</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Toast_Variant__c.field-meta.xml
<CustomField>
    <fullName>Toast_Variant__c</fullName>
    <description>Changes the appearance of the notice. Toasts inherit styling from toasts in the Lightning Design System. Valid values are: info (default), success, warning, and error.</description>
    <inlineHelpText>Changes the appearance of the notice. Toasts inherit styling from toasts in the Lightning Design System. Valid values are: info (default), success, warning, and error.</inlineHelpText>
    <label>Toast Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
            <value>
                <fullName>warning</fullName>
            </value>
            <value>
                <fullName>error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HighlightBadgesService.cls
/************************************************************************
 * @description The HighlightBadgesService provides badges relevant to a particular user and record page
 * 
 * @author SerkinSolutions
 * @date 2024
 ************************************************************************/
public with sharing class HighlightBadgesService {

    public Id displayRecordId {get; private set;}
    public String displayObjectType {get; private set;}

    public HighlightBadgesService(String recordId, String sObjectType) {
        this.displayRecordId = Id.valueOf( recordId );
        this.displayObjectType = sObjectType;
    }

    /****************************************************
     * Constants
     ****************************************************/
    // Platform cache
    private static final String CACHE_KEY_PREFIX = 'bdgs';
    private static final String CACHE_PARTITION_NAME = 'HighlightBadges';

    // Alerts
    private static final String ALERT_FREQUENCY_ALWAYS = 'Always';
    private static final String ALERT_TYPE_TOAST = 'Toast';

    // Badge styles and display
    private static final String DEFAULT_BACKGROUND_COLOR = '#D3D3D3';
    private static final String DEFAULT_LABEL_COLOR = '#000000';
    private static final String DEFAULT_ICON_NAME = 'utility:info';
    private static final String DEFAULT_BADGE_FIELDSET = 'Name';
    private static final String MERGE_FIELD_REGEX = '\\{!.+?\\}';

    /**
     * Platform Cache - Session partition
     */
    private static Cache.SessionPartition sessionCachePartition;

    /**
     * User id of running user
     * Allows for :userId to be used in badge definition queries
     */
    private static Id userId = UserInfo.getUserId();

    /**
     * A map of field names to their common ancestor id
     * The field name is the api path from source to ancestor object
     * The ancestor id is the record id at the end of it
     */
    private Map<String, Id> mapAncestorIds;

    /****************************************************
     * Get active highlight badges for the display record id
     ****************************************************/
    public List<HighlightBadge> getBadges() {
        List<Highlight_Badge_Definition__c> lstBadgeDefinitions = queryForBadgeDefinitions(
            displayObjectType, null
        );
        List<HighlightBadge> lstBadges = getBadgeWrappers(lstBadgeDefinitions);
        return lstBadges;
    }

    /****************************************************
     * Get a previewed, inactive badge, along with all active 
     * badges for the display record id.
     ****************************************************/
    public List<HighlightBadge> getBadges(Id previewDefinitionId) {
        List<Highlight_Badge_Definition__c> lstBadgeDefinitions = queryForBadgeDefinitions(
            displayObjectType, new Set<Id>{ previewDefinitionId }
        );
        List<HighlightBadge> lstBadges = getBadgeWrappers(lstBadgeDefinitions);
        return lstBadges;
    }

    /****************************************************
     * Get a list of HighlightBadge data wrappers.
     ****************************************************/
    private List<HighlightBadge> getBadgeWrappers(
        List<Highlight_Badge_Definition__c> lstBadgeDefinitions
    ) {
        List<HighlightBadge> lstBadges = new List<HighlightBadge>();
        Map<String, Id> mapFieldNameToAncestorId = getAncestorIdMap(lstBadgeDefinitions);

        // For each badge definition, get relevant badges
        for (Highlight_Badge_Definition__c definition : lstBadgeDefinitions) {
            // Check query limit to ensure current query won't exceed it
            if (Limits.getQueries() == Limits.getLimitQueries()) {
                break;
            }

            String ancestorId = definition.Common_Ancestor_Object__c == definition.Display_Object__c 
                ? displayRecordId 
                : mapFieldNameToAncestorId.get(definition.Display_to_Ancestor_Path__c);
            HighlightBadgeQueryBuilder queryBuilder = new HighlightBadgeQueryBuilder(
                definition, 
                displayRecordId, 
                ancestorId
            );
            String strQuery = queryBuilder.getQueryString();

            List<SObject> queryResults;
            try {
                queryResults = Database.query(strQuery, AccessLevel.USER_MODE);
            } catch (System.QueryException ex) {
                // User does not have required object, FLS, or sharing access
                continue;
            }

            lstBadges.addAll( 
                constructHighlightBadges(queryResults, definition) 
            );
        }
        
        return lstBadges;
    }

    /****************************************************
     * Builds and returns a HighlightBadge object from the SObject and definition
     ****************************************************/
    private List<HighlightBadge> constructHighlightBadges(
        List<SObject> objs, 
        Highlight_Badge_Definition__c definition
    ) {
        List<HighlightBadge> lstBadges = new List<HighlightBadge>();

        // Create set to store label names to avoid duplicates
        Set<String> setLabelNames = new Set<String>();

        for (SObject obj : objs) {
            HighlightBadge badge = new HighlightBadge();
            badge.definitionId = definition.Id;
            badge.recordId = obj.Id;
            badge.sObjectType = definition.Source_Object__c;
            badge.sObjectTypeLabel = GlobalDescribeService.getDescribe(badge.sObjectType).getLabel();
            badge.label = getBadgeLabel(definition, obj);
            // Prevent duplicates
            if (setLabelNames.contains(badge.label)) {
                continue;
            } else {
                setLabelNames.add(badge.label);
            }
            badge.iconName = getBadgeIconName(definition);
            badge.styles = getBadgeColorStyle(definition) + getBadgeLabelStyle(definition);
            badge.backgroundColor = definition.Background_Color__c ?? DEFAULT_BACKGROUND_COLOR;
            badge.labelColor = definition.Label_Color__c ?? DEFAULT_LABEL_COLOR;
            badge.fieldSet = String.isBlank(definition.Source_Detail_Fields__c)
                ? getDefaultFieldSet(definition.Source_Object__c)
                : definition.Source_Detail_Fields__c.replaceAll('\\s+', '');

            // Badge has alert if alerts are enabled and either set to show every time, 
            // or this is the first user visit
            if (
                definition.Alert__c && 
                (definition.Alert_Frequency__c == ALERT_FREQUENCY_ALWAYS || verifyFirstBadgeView(badge.recordId))
            ) {
                badge.hasAlert = true;
                badge.alertMessage = getBadgeAlertMessage(definition, obj);
                badge.alertType = definition.Alert_Type__c ?? null;
                if (badge.alertType == ALERT_TYPE_TOAST) {
                    badge.toastVariant = definition.Toast_Variant__c;
                    badge.toastMode = definition.Toast_Mode__c;
                    badge.includeLabelInToast = definition.Include_Label_in_Toast__c;
                }

                // Confetti settings
                if (definition.Confetti__c) {
                    badge.hasConfetti = true;
                    badge.confettiNumber = definition.Confetti_Volume__c ?? 'normal';
                    badge.confettiSize = definition.Confetti_Size__c ?? 'medium';
                }
            }

            // Add actions to badge
            badge.actions = constructBadgeActions(definition, obj);
            
            lstBadges.add(badge);
        }

        return lstBadges;
    }

    /****************************************************
     * Wrap child Highlight_Badge_Actions__r as HighlightBadge.Action objects
     ****************************************************/
    private List<HighlightBadge.Action> constructBadgeActions(
        Highlight_Badge_Definition__c definition,
        SObject record
    ) {
        List<HighlightBadge.Action> lstActions = new List<HighlightBadge.Action>();
        for (Highlight_Badge_Action__c hba : definition.Highlight_Badge_Actions__r) {
            HighlightBadge.Action a = new HighlightBadge.Action();
            a.id = hba.Id;
            a.sortOrder = hba.Sort_Order__c;
            a.recordTypeName = hba.RecordType.Name;
            a.navigationType = hba.Navigation_Type__c;
            a.url = hba.Navigation_Type__c == 'View Source Record' ? '/' + record.Id : hba.URL__c;
            a.flowType = hba.Flow_Type__c;
            a.flowApiName = hba.Flow_API_Name__c;
            a.includeRecordId = hba.Include_Record_ID__c;
            a.includeDisplayRecordId = hba.Include_Display_Record_ID__c;
            a.label = hba.Label__c;
            a.variant = hba.Variant__c;
            a.iconName = hba.Icon_Name__c;
            a.iconPosition = hba.Icon_Position__c;
            lstActions.add(a);
        }
        return lstActions;
    }

    /****************************************************
     * Map of api paths to ancestor object id
     * Find the ancestor record id from the Source to Ancestor Path
     ****************************************************/
    private Map<String, Id> getAncestorIdMap(
        List<Highlight_Badge_Definition__c> lstDefinitions
    ) {
        if (mapAncestorIds != null) {
            return mapAncestorIds;
        }
        
        mapAncestorIds = new Map<String, Id>();
        Set<String> setAncestorFields = new Set<String>();
        for (Highlight_Badge_Definition__c def : lstDefinitions) {
            if (def.Display_Object__c != def.Common_Ancestor_Object__c) {
                setAncestorFields.add(def.Display_to_Ancestor_Path__c);
            }
        }

        // No need to query if the only ancestor id is the record id of the display record
        if (setAncestorFields.isEmpty()) {
            return mapAncestorIds;
        }

        List<String> lstAncestorFields = new List<String>();
        lstAncestorFields.addAll(setAncestorFields);

        String strQuery = 'SELECT ' + String.join(lstAncestorFields, ', ') + 
            ' FROM ' + displayObjectType + 
            ' WHERE Id = \'' + displayRecordId + '\' LIMIT 1';

        List<SObject> lstObjs = Database.query(strQuery, AccessLevel.USER_MODE);
        for (String fieldName : setAncestorFields) {
            // If the field path traverses objects, we have to do some more work to find the record id
            if (fieldName.contains('.')) {
                // Resolve field path that uses dot notation
                mapAncestorIds.put(fieldName, resolveFieldPath(lstObjs[0], fieldName));
            } else {
                // Direct field access
                mapAncestorIds.put(fieldName, (Id) lstObjs[0].get(fieldName) );
            }
        }
        return mapAncestorIds;
    }

    /****************************************************
     * Returns the value for a given sObject and field path
     * @param sObject The base object
     * @param String The field path for the value to return
     ****************************************************/
    private static Id resolveFieldPath(
        sObject record,
        String fieldPath
    ) {
        List<String> pathParts = fieldPath.split('\\.');
        sObject currentRecord = record;

        for (Integer i = 0; i < pathParts.size() - 1; i++) {
            String part = pathParts[i];
            currentRecord = (sObject) currentRecord.getSObject(part);

            if (currentRecord == null) {
                // Early exit if the relationship does not exist or is null
                return null;
            }
        }

        // Get final part of string to find value from the top level object
        String finalPart = pathParts[pathParts.size() - 1];
        return (Id) currentRecord.get(finalPart);
    }

    /****************************************************
     * Returns the badge label for a single definition
     * @param Highlight_Badge_Definition__c The definition record
     *     to construct a query for
     * @param SObject The api name of the sObject type being queried
     ****************************************************/
     public static String getBadgeLabel(
        Highlight_Badge_Definition__c definition, 
        SObject obj
    ) {
        String badgeLabel = definition.Label__c.contains('{!')
            ? replaceMergeFieldsWithValues(definition.Label__c, obj) 
            : definition.Label__c;
        return badgeLabel;
    }

    /****************************************************
     * Returns the badge alert message for a single definition
     * @param Highlight_Badge_Definition__c The definition record
     *     to construct a query for
     * @param SObject The api name of the sObject type
     ****************************************************/
    public static String getBadgeAlertMessage(
        Highlight_Badge_Definition__c definition, 
        SObject obj
    ) {
        String alertMessage;
        if (
            definition.Alert__c && 
            !String.isBlank(definition.Alert_Message__c) &&
            definition.Alert_Message__c.contains('{!')
        ) {
            alertMessage = replaceMergeFieldsWithValues(
                definition.Alert_Message__c, 
                obj
            );
        } else {
            alertMessage = definition.Alert_Message__c;
        }
        return alertMessage;
    }

    /****************************************************
     * Returns a string that can be referenced in an html style attribute
     *     to display the badge's defined background color (or default)
     * @param Highlight_Badge_Definition__c The definition record
     *     to get the badge color for
     ****************************************************/
    public static String getBadgeColorStyle(
        Highlight_Badge_Definition__c definition
    ) {
        String hexColor = definition.Background_Color__c != null ? definition.Background_Color__c : DEFAULT_BACKGROUND_COLOR;
        String badgeColorStyle = '--sds-c-badge-color-background:' + hexColor + ';';
        return badgeColorStyle;
    }

    /****************************************************
     * Returns a string that can be referenced in an html style attribute
     *     to display the badge's defined label color (or default)
     * @param Highlight_Badge_Definition__c The definition record
     *     to get the label color for
     ****************************************************/
    public static String getBadgeLabelStyle(
        Highlight_Badge_Definition__c definition
    ) {
        String labelHexColor = definition.Label_Color__c != null ? definition.Label_Color__c : DEFAULT_LABEL_COLOR;
        String badgeLabelStyle = '--sds-c-badge-text-color:' + labelHexColor + ';--slds-c-badge-icon-color-foreground:' + labelHexColor;
        return badgeLabelStyle;
    }

    /****************************************************
     * Returns the name of the icon to display for this badge
     * @param Highlight_Badge_Definition__c The definition record
     *     to get the badge icon for
     ****************************************************/
    public static String getBadgeIconName(
        Highlight_Badge_Definition__c definition
    ) {
        String iconName = !String.isBlank(definition.Icon_Name__c) ? definition.Icon_Name__c : DEFAULT_ICON_NAME;
        return iconName;
    }

    /****************************************************
     * Returns true if this is the running user's first visit to this
     *     record page in the current session and caches the current
     *     visit. Returns false if a visit is found in the session cache
     * @param String Record Id
     ****************************************************/
    private static Boolean verifyFirstBadgeView(
        String badgeId
    ) {
        Boolean isFirstView = true;
        // Create cache key out of user and badge ids
        String userId = UserInfo.getUserId();
        String cacheBadgeKey = CACHE_KEY_PREFIX + userId + badgeId;
        // Create instance of session partition
        Cache.SessionPartition part = getSessionCachePartition( Util.prefixCacheNamespace(CACHE_PARTITION_NAME) );
        if (part.contains(cacheBadgeKey)) {
            isFirstView = false;
        } else {
            part.put(cacheBadgeKey, Datetime.now());
        }
        return isFirstView;
    }

    /****************************************************
     * Ensures session cache partition is only retrieved a single time
     * @param String Session cache partition name
     ****************************************************/
    private static Cache.SessionPartition getSessionCachePartition(
        String cachePartitionName
    ) {
        if (sessionCachePartition == null) {
            sessionCachePartition = Cache.Session.getPartition(cachePartitionName);
        }
        return sessionCachePartition;
    }

    /****************************************************
     * Returns the original string with merge fields substituted for their values
     * @param String String containing merge fields to be replaced
     * @param SObject The api name of the sObject type
     ****************************************************/
    @TestVisible
    private static String replaceMergeFieldsWithValues(
        String input,
        SObject obj
    ) {
        String result = input;
        Map<String, Schema.SObjectField> fieldMap = obj.getSObjectType().getDescribe().fields.getMap();
        Map<String,Object> mapObjFields = obj.getPopulatedFieldsAsMap();

        Pattern p = Pattern.compile(MERGE_FIELD_REGEX);
        Matcher m = p.matcher(result);

        while(m.find()) {
            String fieldApiName = m.group().substring(2, m.group().length() - 1);
            if (mapObjFields.containsKey(fieldApiName)) {
                Object fieldValue = mapObjFields.get(fieldApiName);
                Schema.DescribeFieldResult fieldDescribe = fieldMap.get(fieldApiName).getDescribe();
                String formattedValue = formatFieldValue(fieldValue, fieldDescribe);
                result = result.replace(m.group(0), formattedValue);
            } else {
                result = result.replace(m.group(0), '');
            }
        }
        return result;
    }

    /****************************************************
     * Format field values based on data type
     * @param Object The field value
     * @param Schema.DescribeFieldResult field describe for the provided field
     * @return String Formatted field value
     ****************************************************/
    @TestVisible
    private static String formatFieldValue(
        Object fieldValue, 
        Schema.DescribeFieldResult fieldDescribe
    ) {
        if (fieldValue == null) return '';

        Schema.DisplayType fieldType = fieldDescribe.getType();

        if (fieldType == Schema.DisplayType.DATE) {
            Date dateValue = (Date) fieldValue;
            return dateValue.format();
        } else if (fieldType == Schema.DisplayType.DATETIME) {
            Datetime datetimeValue = (Datetime) fieldValue;
            return datetimeValue.format();
        } else if (fieldType == Schema.DisplayType.CURRENCY) {
            Decimal currencyValue = (Decimal) fieldValue;
            return '$' + currencyValue.format();
        } else {
            return String.valueOf(fieldValue);
        }
    }

    /****************************************************
     * Returns a valid, default field set for any sobject type
     * @param String The api name of the sObject type
     * @return String A comma-separated string of default fields
     ****************************************************/
    public static String getDefaultFieldSet(String sObjectType) {
        return GlobalDescribeService.getSObjectNameField(sObjectType);
    }

    /****************************************************
     * Query for active badge definition records
     * @param displayObject The api name of the source object
     * @param additionalDefinitionIds Optionally, include additional ids
     ****************************************************/
    private List<Highlight_Badge_Definition__c> queryForBadgeDefinitions(
        String displayObject,
        Set<Id> additionalDefinitionIds
    ) {
        return [
            SELECT Id,
                   Name,
                   Display_Object__c,
                   Common_Ancestor_Object__c,
                   Source_Object__c,
                   Source_to_Ancestor_Path__c,
                   Display_to_Ancestor_Path__c,
                   Filter_Criteria__c,
                   Order_By__c,
                   Limit__c,
                   Source_Detail_Fields__c,
                   Label__c,
                   Icon_Name__c,
                   Background_Color__c,
                   Label_Color__c,
                   Alert__c,
                   Alert_Message__c,
                   Alert_Type__c,
                   Toast_Variant__c,
                   Toast_Mode__c,
                   Alert_Frequency__c,
                   Include_Label_in_Toast__c,
                   Confetti__c,
                   Confetti_Volume__c,
                   Confetti_Size__c,
                   (SELECT Id,
                           Sort_Order__c,
                           RecordType.Name,
                           Navigation_Type__c,
                           URL__c,
                           Flow_Type__c,
                           Flow_API_Name__c,
                           Include_Record_ID__c,
                           Include_Display_Record_ID__c,
                           Label__c,
                           Variant__c,
                           Icon_Name__c,
                           Icon_Position__c
                      FROM Highlight_Badge_Actions__r
                     WHERE Active__c = true
                     ORDER BY Sort_Order__c ASC NULLS LAST)
              FROM Highlight_Badge_Definition__c
             WHERE Display_Object__c = :displayObject
               AND (Active__c = true OR Id IN :additionalDefinitionIds)
              WITH USER_MODE
             ORDER BY Sort_Order__c ASC NULLS LAST
             LIMIT 100
        ];
    }

}