force-app/main/default/objects/Highlight_Badge_Action__c/Highlight_Badge_Action__c.object-meta.xml
<CustomObject>
    <description>A customizable action associated with a Highlight Badge that allows for user interaction and automated tasks</description>
    <label>Highlight Badge Action</label>
    <nameField>
        <label>Highlight Badge Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Highlight_Badge_Definition__c.field-meta.xml
<CustomField>
    <fullName>Highlight_Badge_Definition__c</fullName>
    <label>Highlight Badge Definition</label>
    <referenceTo>Highlight_Badge_Definition__c</referenceTo>
    <relationshipLabel>Highlight Badge Actions</relationshipLabel>
    <relationshipName>Highlight_Badge_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/Highlight_Badge_Definition__c.object-meta.xml
<CustomObject>
    <description>Configuration for an individual highlight badge</description>
    <label>Highlight Badge Definition</label>
    <nameField>
        <label>Highlight Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HighlightBadgeActionsMgrController_Test.cls
@IsTest
private class HighlightBadgeActionsMgrController_Test {

    @TestSetup
    static void makeData() {
        List<Highlight_Badge_Definition__c> lstDefinitions = TestDataFactory.getTestDefinitions();
        insert lstDefinitions;

        insert TestDataFactory.getTestActions(lstDefinitions);
    }

    @IsTest 
    static void testGetActions() {
        Highlight_Badge_Definition__c definitionWithActions = [
            SELECT Id, (SELECT Id FROM Highlight_Badge_Actions__r)
              FROM Highlight_Badge_Definition__c
             LIMIT 1
        ];

        User u = TestDataFactory.createTestUser('Rey', 'Ordonez', 'Admin');

        List<Highlight_Badge_Action__c> returnedActions;
        Test.startTest();
        System.runAs(u) {
            returnedActions = HighlightBadgeActionsMgrController.getActions(
                definitionWithActions.Id
            );
        }
        Test.stopTest();

        Assert.areEqual(
            definitionWithActions.Highlight_Badge_Actions__r.size(), 
            returnedActions.size(), 
            'Should have received all the actions for the provided definition'
        );
    }

}