force-app/main/default/objects/Highlight_Badge_Action__c/Highlight_Badge_Action__c.object-meta.xml
<CustomObject>
    <description>A customizable action associated with a Highlight Badge that allows for user interaction and automated tasks</description>
    <label>Highlight Badge Action</label>
    <nameField>
        <label>Highlight Badge Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_API_Name__c</fullName>
    <label>Flow API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Flow_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Type__c</fullName>
    <label>Flow Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autolaunched Flow</fullName>
            </value>
            <value>
                <fullName>Screen Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Highlight_Badge_Definition__c.field-meta.xml
<CustomField>
    <fullName>Highlight_Badge_Definition__c</fullName>
    <label>Highlight Badge Definition</label>
    <referenceTo>Highlight_Badge_Definition__c</referenceTo>
    <relationshipLabel>Highlight Badge Actions</relationshipLabel>
    <relationshipName>Highlight_Badge_Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>Use icon names from the SLDS library (e.g. standard:actions_and_buttons)</description>
    <inlineHelpText>Use icon names from the SLDS library (e.g. standard:actions_and_buttons)</inlineHelpText>
    <label>Icon Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Icon_Position__c.field-meta.xml
<CustomField>
    <fullName>Icon_Position__c</fullName>
    <label>Icon Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left</fullName>
                <default>true</default>
                <label>Left</label>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Include_Display_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Include_Display_Record_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the Record ID of the current Display Object record the user is viewing will be provided to the displayRecordId input variable.</description>
    <inlineHelpText>If checked, the Record ID of the current Display Object record the user is viewing will be provided to the displayRecordId input variable.</inlineHelpText>
    <label>Include Display Record ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Include_Source_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Include_Source_Record_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, the Record ID of the badge&apos;s source record will be provided to the sourceRecordId input variable.</description>
    <inlineHelpText>If checked, the Record ID of the badge&apos;s source record will be provided to the sourceRecordId input variable.</inlineHelpText>
    <label>Include Source Record ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Navigation_Type__c.field-meta.xml
<CustomField>
    <fullName>Navigation_Type__c</fullName>
    <label>Navigation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Knowledge Article</fullName>
            </value>
            <value>
                <fullName>Source Record</fullName>
            </value>
            <value>
                <fullName>Web Page</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Determines the order in which the action appears for its highlight badge. Lowest numbers appear first; null values appear last.</description>
    <inlineHelpText>Determines the order in which the action appears for its highlight badge. Lowest numbers appear first; null values appear last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>base</fullName>
            </value>
            <value>
                <fullName>neutral</fullName>
            </value>
            <value>
                <fullName>brand</fullName>
            </value>
            <value>
                <fullName>brand-outline</fullName>
            </value>
            <value>
                <fullName>destructive</fullName>
            </value>
            <value>
                <fullName>destructive-text</fullName>
            </value>
            <value>
                <fullName>inverse</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Action__c/recordTypes/Flow.recordType-meta.xml
<RecordType>
    <fullName>Flow</fullName>
    <active>true</active>
    <description>Launch a flow</description>
    <label>Flow</label>
</RecordType>

force-app/main/default/objects/Highlight_Badge_Definition__c/Highlight_Badge_Definition__c.object-meta.xml
<CustomObject>
    <description>Configuration for an individual highlight badge</description>
    <label>Highlight Badge Definition</label>
    <nameField>
        <label>Highlight Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>Use icon names from the SLDS library (e.g. utility:alert)</description>
    <inlineHelpText>Use icon names from the SLDS library (e.g. utility:alert)</inlineHelpText>
    <label>Icon Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The label of the displayed badge</description>
    <inlineHelpText>The label of the displayed badge</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Determines the order in which badges of this type will appear. Lowest numbers appear first; null values appear last.</description>
    <inlineHelpText>Determines the order in which badges of this type will appear. Lowest numbers appear first; null values appear last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HighlightBadgeActionsMgrController.cls
/************************************************************************
 * @description Controller for the highlightBadgeActionsManager LWC
 * 
 * @author SerkinSolutions
 * @date 2024
 ************************************************************************/
public with sharing class HighlightBadgeActionsMgrController {

    private static final String FLOW_PROCESS_TYPE = 'Flow';
    
    @AuraEnabled(cacheable=true)
    public static List<Highlight_Badge_Action__c> getActions(String recordId) {
        try {
            return getRelatedActions(recordId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<FlowOption> getFlowOptions() {
        try {
            List<FlowDefinitionView> fdvs = getActiveFlows();
            return createFlowOptionsFromDefinitionViews(fdvs);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static List<FlowOption> createFlowOptionsFromDefinitionViews(List<FlowDefinitionView> fdvs) {
        List<FlowOption> flowOptions = new List<FlowOption>();
        for (FlowDefinitionView fdv : fdvs) {
            FlowOption option = new FlowOption();
            option.label = fdv.Label;
            option.value = getQualifiedApiName(fdv);
        }
        return flowOptions;
    }

    private static String getQualifiedApiName(
        FlowDefinitionView fdv
    ) {
        return String.isEmpty(fdv.NamespacePrefix) 
            ? fdv.ApiName 
            : fdv.NamespacePrefix + '__' + fdv.ApiName;
    }

    private static List<FlowDefinitionView> getActiveFlows() {
        return [
            SELECT ApiName, Label, NamespacePrefix
              FROM FlowDefinitionView
             WHERE IsActive = true
               AND ProcessType = :FLOW_PROCESS_TYPE
              WITH SYSTEM_MODE
             ORDER BY Label ASC
        ];
    }

    private static List<Highlight_Badge_Action__c> getRelatedActions(String recordId) {
        return [
            SELECT Id,
                   Sort_Order__c,
                   RecordType.Name,
                   Navigation_Type__c,
                   URL__c,
                   Flow_Type__c,
                   Flow_API_Name__c,
                   Include_Source_Record_ID__c,
                   Include_Display_Record_ID__c,
                   Label__c,
                   Variant__c,
                   Icon_Name__c,
                   Icon_Position__c
              FROM Highlight_Badge_Action__c 
             WHERE Highlight_Badge_Definition__c = :recordId
              WITH USER_MODE
             LIMIT 10000
        ];
    }

    public class FlowOption {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;
    }

}