force-app/main/default/objects/Highlight_Badge_Definition__c/Highlight_Badge_Definition__c.object-meta.xml
<CustomObject>
    <description>Configuration for an individual highlight badge</description>
    <label>Highlight Badge Definition</label>
    <nameField>
        <label>Highlight Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, an alert will display to the user when the page loads</description>
    <inlineHelpText>If checked, an alert will display to the user when the page loads</inlineHelpText>
    <label>Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Alert_Message__c.field-meta.xml
<CustomField>
    <fullName>Alert_Message__c</fullName>
    <description>When Alert is checked, this message displays in the pop-up window a page loads. Use {!My_Custom_Field__c} syntax to display merged values from the child object</description>
    <inlineHelpText>When Alert is checked, this message displays in the pop-up window a page loads. Use {!My_Custom_Field__c} syntax to display merged values from the child object</inlineHelpText>
    <label>Alert Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <description>Additional criteria to include in the WHERE clause of the SOQL query</description>
    <inlineHelpText>Additional criteria to include in the WHERE clause of the SOQL query</inlineHelpText>
    <label>Filter Criteria</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The label of the displayed badge</description>
    <inlineHelpText>The label of the displayed badge</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <description>Optionally, define the order in which badges are displayed (e.g. LastModifiedDate DESC)</description>
    <inlineHelpText>Optionally, define the order in which badges are displayed (e.g. LastModifiedDate DESC)</inlineHelpText>
    <label>Order By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_Detail_Fields__c.field-meta.xml
<CustomField>
    <fullName>Source_Detail_Fields__c</fullName>
    <description>Enter API field names, separated by commas, for any fields from the Source Object that should be displayed when a user selects a badge</description>
    <inlineHelpText>Enter API field names, separated by commas, for any fields from the Source Object that should be displayed when a user selects a badge</inlineHelpText>
    <label>Source Detail Fields</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>The API Name of the Salesforce object that is the source of the badge information. For example, a badge on a contact record displaying open cases would have a Source Object of &apos;Case&apos;.</description>
    <inlineHelpText>The API Name of the Salesforce object that is the source of the badge information. For example, a badge on a contact record displaying open cases would have a Source Object of &apos;Case&apos;.</inlineHelpText>
    <label>Source Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_to_Parent_Path__c.field-meta.xml
<CustomField>
    <fullName>Source_to_Parent_Path__c</fullName>
    <description>The API path from the Source Object to the Parent Object</description>
    <inlineHelpText>The API path from the Source Object to the Parent Object</inlineHelpText>
    <label>Source to Parent Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HighlightBadgeQueryBuilder.cls
/**
 * Used to construct queries from Highlight Badge Definition configuration
 * @date 2024
 */
public with sharing class HighlightBadgeQueryBuilder {

    /****************************************************
     * Constants
     ****************************************************/
    private static final String DEFAULT_BACKGROUND_COLOR = '#D3D3D3';
    private static final String DEFAULT_LABEL_COLOR = '#000000';
    private static final String DEFAULT_ICON_NAME = 'utility:info';
    private static final String MERGE_FIELD_REGEX = '\\{!.+?\\}';

    private Highlight_Badge_Definition__c definition;
    private Id recordId;
    private Id parentId;

    public HighlightBadgeQueryBuilder(
        Highlight_Badge_Definition__c definition, 
        Id recordId, 
        Id parentId
    ) {
        this.definition = definition;
        this.recordId = recordId;
        this.parentId = parentId;
    }

    public String getQueryString() {
        String queryString = getQueryFromDefinition();
        return queryString;
    }

    /****************************************************
     * Returns a soql query string, constructed from highlight badge definition properties
     * @param Highlight_Badge_Definition__c The definition record to construct a query for
     ****************************************************/
    private String getQueryFromDefinition() {
        // SELECT
        String query = 'SELECT Id ';
        Set<String> setDetailFields = getFieldsForSelector(definition);
        for (String field : setDetailFields) {
            query += ', ' + field + ' ';
        }

        // FROM
        query += 'FROM ' + definition.Source_Object__c + ' ';

        // WHERE
        query += 'WHERE ' + definition.Source_to_Parent_Path__c + ' = :parentId ';
        if (!String.isBlank(definition.Filter_Criteria__c)) {
            query += 'AND ' + definition.Filter_Criteria__c + ' ';
        }
        
        // ORDER BY
        if (!String.isBlank(definition.Order_By__c)) {
            query += 'ORDER BY ' + definition.Order_By__c;
        }
        
        System.debug(':::: query --> ' + query);
        return query;
    }

    /****************************************************
     * Returns a set of strings with each of the field names to include
     *     in the SELECT statement of the query
     * @param Contact_Badge_Definition__mdt The definition record
     *     to get selector fields for
     ****************************************************/
     private Set<String> getFieldsForSelector(
        Highlight_Badge_Definition__c definition
    ) {
        Set<String> fieldsForSelector = new Set<String>();
        // If displaying a label with merge fields, add the fields to the query
        if (
            !String.isBlank(definition.Label__c) && 
            definition.Label__c.contains('{!')
        ) {
            fieldsForSelector.addAll(
                getMergeFieldsFromString(definition.Label__c)
            );
        }
        // If displaying an alert, check for merge fields to add to query
        if (
            definition.Alert__c && 
            !String.isBlank(definition.Alert_Message__c) &&
            definition.Alert_Message__c.contains('{!')
        ) {
            fieldsForSelector.addAll(
                getMergeFieldsFromString(definition.Alert_Message__c)
            );
        }
        
        // Add all additional fields for the modal
        if (!String.isBlank(definition.Source_Detail_Fields__c)) {
            fieldsForSelector.addAll(definition.Source_Detail_Fields__c.replaceAll('\\s+', '').split(','));
        } else {
            fieldsForSelector.add('Name');
        }
        System.debug('::::: got fields for selector --> ' + fieldsForSelector);
        return fieldsForSelector;
    }

    /****************************************************
     * Returns a set of strings with each of the merge fields contained in the original string
     * @param String String containing merge fields
     ****************************************************/

     private Set<String> getMergeFieldsFromString(
        String input
    ) {
        Set<String> setMergeFields = new Set<String>();
        Pattern p = Pattern.compile(MERGE_FIELD_REGEX);
        Matcher m = p.matcher(input);
        while(m.find()) {
            String mergeFieldApiName = m.group().substring(
                2, 
                m.group().length() - 1
            );
            setMergeFields.add(mergeFieldApiName);
        }
        return setMergeFields;
    }


}