force-app/main/default/objects/Highlight_Badge_Definition__c/Highlight_Badge_Definition__c.object-meta.xml
<CustomObject>
    <description>Configuration for an individual highlight badge</description>
    <label>Highlight Badge Definition</label>
    <nameField>
        <label>Highlight Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Highlight Badge Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A highlight badge definition must be active to be displayed on record pages</description>
    <inlineHelpText>A highlight badge definition must be active to be displayed on record pages</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Common_Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Common_Parent_Object__c</fullName>
    <label>Common Parent Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Display_Object__c.field-meta.xml
<CustomField>
    <fullName>Display_Object__c</fullName>
    <description>The API Name of the Salesforce object where the Highlight Badge will appear</description>
    <inlineHelpText>The API Name of the Salesforce object where the Highlight Badge will appear</inlineHelpText>
    <label>Display Object</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Display_to_Parent_Path__c.field-meta.xml
<CustomField>
    <fullName>Display_to_Parent_Path__c</fullName>
    <description>The API path from the Display Object to the Parent Object</description>
    <inlineHelpText>The API path from the Display Object to the Parent Object</inlineHelpText>
    <label>Display to Parent Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <description>Additional criteria to include in the WHERE clause of the SOQL query</description>
    <inlineHelpText>Additional criteria to include in the WHERE clause of the SOQL query</inlineHelpText>
    <label>Filter Criteria</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The label of the displayed badge</description>
    <inlineHelpText>The label of the displayed badge</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_Detail_Fields__c.field-meta.xml
<CustomField>
    <fullName>Source_Detail_Fields__c</fullName>
    <description>Enter API field names, separated by commas, for any fields from the Source Object that should be displayed when a user selects a badge</description>
    <inlineHelpText>Enter API field names, separated by commas, for any fields from the Source Object that should be displayed when a user selects a badge</inlineHelpText>
    <label>Source Detail Fields</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>The API Name of the Salesforce object that is the source of the badge information. For example, a badge on a contact record displaying open cases would have a Source Object of &apos;Case&apos;.</description>
    <inlineHelpText>The API Name of the Salesforce object that is the source of the badge information. For example, a badge on a contact record displaying open cases would have a Source Object of &apos;Case&apos;.</inlineHelpText>
    <label>Source Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Highlight_Badge_Definition__c/fields/Source_to_Parent_Path__c.field-meta.xml
<CustomField>
    <fullName>Source_to_Parent_Path__c</fullName>
    <description>The API path from the Source Object to the Parent Object</description>
    <inlineHelpText>The API path from the Source Object to the Parent Object</inlineHelpText>
    <label>Source to Parent Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HighlightBadgesService_Test.cls
@IsTest
private class HighlightBadgesService_Test {

    @TestSetup
    static void makeData() {
        List<Account> lstAccounts = TestDataFactory.createAccounts(1);
        insert lstAccounts;

        List<Contact> lstContacts = TestDataFactory.createContacts(lstAccounts, 1);
        insert lstContacts;

        List<Case> lstCases = TestDataFactory.createCases(lstContacts, 1);
        insert lstCases;

        List<Opportunity> lstOpps = TestDataFactory.createOpportunities(lstContacts, 1);
        insert lstOpps;

        insert TestDataFactory.getTestDefinitions();
    }

    @IsTest
    static void testConstructor() {
        String objType = 'Account';
        Account acc = TestDataFactory.createAccounts(1).get(0);
        insert acc;
        Test.startTest();
        HighlightBadgesService serv = new HighlightBadgesService(acc.Id, objType);
        Test.stopTest();
        Assert.areEqual(acc.Id, serv.displayRecordId, 'Should have set the display record id in the constructor');
        Assert.areEqual(objType, serv.displayObjectType, 'Should have set the display object type in the constructor');
    }

    @IsTest
    static void testGetChildBadge() {
        Contact ct = [SELECT Id, (SELECT Id, CaseNumber FROM Cases WHERE IsClosed = false) FROM Contact LIMIT 1];
        Assert.isFalse(ct.Cases.isEmpty(), 'Test contact should have an open case');

        User u = TestDataFactory.createTestUser('Rey', 'Ordonez', 'Admin');
        Test.startTest();
        System.runAs(u) {
            HighlightBadgesService serv = new HighlightBadgesService(ct.Id, 'Contact');
            List<HighlightBadge> lstBadges = serv.getBadges();

            Assert.isFalse(lstBadges.isEmpty(), 'Should have received a badge');
            HighlightBadge openCaseBadge = new HighlightBadge();
            for (HighlightBadge badge : lstBadges) {
                if (badge.recordId == ct.Cases[0].Id) {
                    openCaseBadge = badge;
                }
            }
            Assert.isTrue(
                openCaseBadge.label.contains(ct.Cases[0].CaseNumber), 
                'The badge label should include the open case number'
            );    
        }
        Test.stopTest();
    }

    @IsTest
    static void testGetSourceBadge() {
        
    }

    @IsTest
    static void testGetCommonParentBadge() {
        Contact ct = [SELECT Id, (SELECT Id FROM Opportunities WHERE Amount > 100) FROM Contact LIMIT 1];
        Assert.isFalse(ct.Opportunities.isEmpty(), 'Test contact should have an eligible opportunity');

        User u = TestDataFactory.createTestUser('Rey', 'Ordonez', 'Admin');
        Test.startTest();
        System.runAs(u) {
            HighlightBadgesService serv = new HighlightBadgesService(ct.Id, 'Contact');
            List<HighlightBadge> lstBadges = serv.getBadges();
            Test.stopTest();
            Boolean hasOppBadge = false;
            for (HighlightBadge badge : lstBadges) {
                if (badge.recordId == ct.Opportunities[0].Id) {
                    hasOppBadge = true;
                }
            }
            Assert.isTrue(
                hasOppBadge, 
                'Should have received a badge for opportunities over $100 from the parent account'
            );
        }
    }

    @IsTest
    static void testNoBadgesForRecord() {
        
    }

    @IsTest
    static void testSOQLLimitHandling() {
        User u = TestDataFactory.createTestUser('Rey', 'Ordonez', 'Admin');

        Contact ct = [SELECT Id, (SELECT Id FROM Opportunities WHERE Amount > 100) FROM Contact LIMIT 1];
        Assert.isFalse(ct.Opportunities.isEmpty(), 'Test contact should have an eligible opportunity');

        Test.startTest();
        System.runas(u) {
            List<Highlight_Badge_Definition__c> lstDefinitions = new List<Highlight_Badge_Definition__c>();
            for (Integer i = 0; i < 101; i++) {
                lstDefinitions.add(
                    new Highlight_Badge_Definition__c(
                        Active__c = true, 
                        Name = 'Opp Over ' + String.valueOf(i), 
                        Display_Object__c = 'Contact', 
                        Source_Object__c = 'Opportunity', 
                        Common_Parent_Object__c = 'Account', 
                        Source_to_Parent_Path__c = 'AccountId', 
                        Display_to_Parent_Path__c = 'AccountId', 
                        Filter_Criteria__c = 'Amount > ' + String.valueOf(i), 
                        Source_Detail_Fields__c = 'Name, StageName, Amount', 
                        Label__c = 'Big Opp'
                    )
                );
            }
            insert lstDefinitions;

            HighlightBadgesService serv = new HighlightBadgesService(ct.Id, 'Contact');
            List<HighlightBadge> lstBadges = serv.getBadges();

            Assert.isFalse(lstBadges.isEmpty(), 'Should have received partial collection of badges');
        }
        Test.stopTest();
    }

}